source("tranplot.R")
x.opt <- tran.est(filter1(count.data,condition,1),condition)

pdf("tran.plot.raw.pdf")
tran.plot(-3,filter1(count.data,condition,1),condition,expression("Variance vs. Mean with No Transformation"))
dev.off()
pdf("tran.plot.log.pdf")
tran.plot(-1,filter1(count.data,condition,1),condition,expression("Variance vs. Mean with Log Transformation"))
dev.off()
pdf("tran.plot.1.pdf")
tran.plot(0.1,filter1(count.data,condition,1),condition,expression(paste("Variance vs. Mean with ",theta," = 0.1")))
dev.off()
pdf("tran.plot.5.pdf")
tran.plot(0.5,filter1(count.data,condition,1),condition,expression(paste("Variance vs. Mean with ",theta," = 0.5")))
dev.off()
pdf("tran.plot.opt.pdf")
tran.plot(x.opt,filter1(count.data,condition,1),condition,expression(paste("Variance vs. Mean with ",theta," = 0.2341")))
dev.off()
