library(devtools)
install_git("https://github.com/plger/RNAontheBENCH", build_vignettes=TRUE)

library(RNAontheBENCH)

data(exampledata)
#dir.create("example")
#write.table(exampleTranscriptLevel,"example/w12.transcripts.quant",sep="\t",quote=F)
#write.table(exampleGeneLevel,"example/w12.genes.quant",sep="\t",quote=F)

jpeg('plot1.jpg')
deSpikein( exampleGeneLevel, method="edgeR", norm="TMM", quantification="Tophat-featureCounts")
dev.off()
jpeg('plot2.jpg')
deSpikein(exampleGeneLevel, method="DESeq", norm="TMM", quantification="Tophat-featureCounts")
dev.off()
jpeg('plot3.jpg')
deSpikein(exampleGeneLevel, method="DESeq2", norm="TMM", quantification="Tophat-featureCounts")
dev.off()
jpeg('plot4.jpg')
deSpikein(exampleGeneLevel, method="voom", norm="TMM", quantification="Tophat-featureCounts")
dev.off()
jpeg('plot5.jpg')
deSpikein(exampleGeneLevel, method="t", norm="TMM", quantification="Tophat-featureCounts")
dev.off()
jpeg('plot6.jpg')
deSpikein(exampleGeneLevel, method="logt", norm="TMM", quantification="Tophat-featureCounts")
dev.off()

# Normalization = Linear
jpeg('plot7.jpg')
deSpikein(exampleGeneLevel, method="edgeR", norm="linear", quantification="Tophat-featureCounts")
dev.off()
jpeg('plot8.jpg')
deSpikein(exampleGeneLevel, method="DESeq", norm="linear", quantification="Tophat-featureCounts")
dev.off()
jpeg('plot9.jpg')
deSpikein(exampleGeneLevel, method="DESeq2", norm="linear", quantification="Tophat-featureCounts")
dev.off()
jpeg('plot10.jpg')
deSpikein(exampleGeneLevel, method="voom", norm="linear", quantification="Tophat-featureCounts")
dev.off()
jpeg('plot11.jpg')
deSpikein(exampleGeneLevel, method="t", norm="linear", quantification="Tophat-featureCounts")
dev.off()
jpeg('plot12.jpg')
deSpikein(exampleGeneLevel, method="logt", norm="linear", quantification="Tophat-featureCounts")
dev.off()

# Normalization = RLE
jpeg('plot13.jpg')
deSpikein(exampleGeneLevel, method="edgeR", norm="RLE", quantification="Tophat-featureCounts")
dev.off()
jpeg('plot14.jpg')
deSpikein(exampleGeneLevel, method="DESeq", norm="RLE", quantification="Tophat-featureCounts")
dev.off()
jpeg('plot15.jpg')
deSpikein(exampleGeneLevel, method="DESeq2", norm="RLE", quantification="Tophat-featureCounts")
dev.off()
jpeg('plot16.jpg')
deSpikein(exampleGeneLevel, method="voom", norm="RLE", quantification="Tophat-featureCounts")
dev.off()
jpeg('plot17.jpg')
deSpikein(exampleGeneLevel, method="t", norm="RLE", quantification="Tophat-featureCounts")
dev.off()
jpeg('plot18.jpg')
deSpikein(exampleGeneLevel, method="logt", norm="RLE", quantification="Tophat-featureCounts")
dev.off()

# Normalization = Upperquartile
jpeg('plot19.jpg')
deSpikein(exampleGeneLevel, method="edgeR", norm="upperquartile", quantification="Tophat-featureCounts")
dev.off()
jpeg('plot20.jpg')
deSpikein(exampleGeneLevel, method="DESeq", norm="upperquartile", quantification="Tophat-featureCounts")
dev.off()
jpeg('plot21.jpg')
deSpikein(exampleGeneLevel, method="DESeq2", norm="upperquartile", quantification="Tophat-featureCounts")
dev.off()
jpeg('plot22.jpg')
deSpikein(exampleGeneLevel, method="voom", norm="upperquartile", quantification="Tophat-featureCounts")
dev.off()
jpeg('plot23.jpg')
deSpikein(exampleGeneLevel, method="t", norm="upperquartile", quantification="Tophat-featureCounts")
dev.off()
jpeg('plot24.jpg')
deSpikein(exampleGeneLevel, method="logt", norm="upperquartile", quantification="Tophat-featureCounts")
dev.off()

# Normalization = None
jpeg('plot25.jpg')
deSpikein(exampleGeneLevel, method="edgeR", norm="none", quantification="Tophat-featureCounts")
dev.off()
jpeg('plot26.jpg')
deSpikein(exampleGeneLevel, method="DESeq", norm="none", quantification="Tophat-featureCounts")
dev.off()
jpeg('plot27.jpg')
deSpikein(exampleGeneLevel, method="DESeq2", norm="none", quantification="Tophat-featureCounts")
dev.off()
jpeg('plot28.jpg')
deSpikein(exampleGeneLevel, method="voom", norm="none", quantification="Tophat-featureCounts")
dev.off()
jpeg('plot29.jpg')
deSpikein(exampleGeneLevel, method="t", norm="none", quantification="Tophat-featureCounts")
dev.off()
jpeg('plot30.jpg')
deSpikein(exampleGeneLevel, method="logt", norm="none", quantification="Tophat-featureCounts")
dev.off()

# Most extreme AUC values
#0.371 (plot11)
#0.385 (plot12)
#0.873 (plot19)
#0.893 (plot4)